### ISSUE TITLE
Result format

### ISSUE THREAD

**Issue by SergioML9** [eyereasoner/EyeClient#1]
Hi Ruben,

Is there any way to get the result of an input in JSON-ld format? I only am able to get it in text format.

Thank you very much !

**Comment by RubenVerborgh** [comment]
Hi Sergio,

This is not possible yet; one problem is that N3 is a superset of RDF 1.0, and not everything (formulas, variables) can be represented in JSON-LD.

Ruben

**Comment by SergioML9** [comment]
And is it possible to parse it with N3.js library?
I need to parse the result for triggering some actions in the development of a task automation service, and I can't think of any other way that parsing it by comparing each fact.

Thank you very much !

**Comment by RubenVerborgh** [comment]
No, not yet; N3.js supports N-Triples, Turtle, N-Quads, TriG, but not N3 at the moment (I know, given the name of the library, I should really speed things up.)

However, I remember that @joachimvh has written an N3–JSON-LD converter, but I don't know whether it is open-source. @joachimvh, can you comment on this?

**Comment by RubenVerborgh** [comment]
The converter code is unfortunately not open source yet, we are investigating whether we can release it.

But what does your input look like? If it doesn't contain variables nor formulas, it's just Turtle, and then it can be parsed with any Turtle parser.

**Comment by SergioML9** [comment]
Oh, what a pity!

I'm working with presence sensor that sends to a mobile app the distance. The mobile app sends to a server the sensor ID and the distance to it, and it generates an EYE input and triggers the EYE result. For example, I have the following rule:

'If I'm near the door, then open the door', that I have written as follows:

![captura de pantalla 2016-01-10 a las 22 16 00](https://cloud.githubusercontent.com/assets/10586800/12224051/d0ecde1e-b7e7-11e5-93b2-32014e0461a1.png)

So, with an input like this:

![captura de pantalla 2016-01-10 a las 22 19 42](https://cloud.githubusercontent.com/assets/10586800/12224076/4cdd4482-b7e8-11e5-9f0d-615a5ee50381.png)

It generates the following result, and this result is what I want to parse:

![captura de pantalla 2016-01-10 a las 22 20 32](https://cloud.githubusercontent.com/assets/10586800/12224089/75175316-b7e8-11e5-93ca-908299bbba9b.png)

And I would like to take the chance to ask how could I generate an instance in EYE (in SPARQL I generate it with BIND). The '<generate_unique_uri_for_action>'is where I want to generate it.

Thank you very much for your help !

**Comment by RubenVerborgh** [comment]
This result is simple Turtle. You can parse this with N3.js or any other
library that supports Turtle.

**Comment by SergioML9** [comment]
Great, I will try to parse it so.

Thank you very much !

**Comment by SergioML9** [comment]
Hi,

Thanks, One additional question, hope not to bother you.

Now EYE server is stateless, so I have to load all the facts & rules before a new inference. Could it be configured to be stateful? 

Related to the previous question, I have seen that N3 parser supports parsing RDF streams. If EYE could generate RDF streams, this would make easy to parse the new facts. Is this possible?

**Comment by RubenVerborgh** [comment]
There is no stateful configuration for the server, however, there you can speed this up by creating an EYE plugin (`eye --plugin`) which contains these facts and rules. Then, alias the `eye` command to EYE with the plugin.

As far as I know, EYE cannot output streams.

**Comment by SergioML9** [comment]
Thanks Ruben !
