### ISSUE TITLE
pass other flags to the server call

### ISSUE THREAD

**Issue by Javingka** [eyereasoner/EyeClient#3]
Hi Ruben

Looking at this html code, specially the `--nope` flag declared at the end.

```
<code>eye 
     <span class="data">input.n3</span>
     <span class="data">input2.n3</span>
     <span class="data">rules.n3</span>
     --query
     <span class="query">query.n3</span> 
     --nope
</code>
```

It make me think is possible to pass other flags to the server call, but looking at the code it doesn't really seem to be the case. Or I'm  missing something?

thanks in advance!.

**Comment by RubenVerborgh** [comment]
> It make me think is possible to pass other flags to the server call, but looking at the code it doesn't really seem to be the case. Or I'm missing something?

It's definitely _possible_, but not implemented at the moment. The default flags of the server (which include `nope`) are assumed.
